plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android' version '2.2.21' apply false
}

android {
    signingConfigs {
        debug {
            storeFile rootProject.file('freezeitapp_key.jks')
            storePassword 'freezeit'
            keyAlias 'freezeit'
            keyPassword 'freezeit'
        }
        release {
            storeFile rootProject.file('freezeitapp_key.jks')
            storePassword 'freezeit'
            keyAlias 'freezeit'
            keyPassword 'freezeit'
        }
    }
    compileSdk 36

    defaultConfig {
        applicationId "io.github.MoWei.Frozen"
        minSdk 29
        targetSdk 34
        versionCode 801115
        versionName "8.1.1-ui-beta15"

        resValue "string", "versionName", "${versionName}"
        signingConfig signingConfigs.release
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
            multiDexEnabled false
        }
    }
    android.applicationVariants.configureEach {
        variant ->
            variant.outputs.configureEach {
                outputFileName = "Frozen.apk"
            }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    buildFeatures {
        viewBinding true
        buildConfig true
    }
    namespace 'io.github.MoWei.Frozen'
    dependenciesInfo {
        includeInApk false
        includeInBundle false
    }
}

dependencies {

    compileOnly 'de.robv.android.xposed:api:82'

    implementation(platform('org.jetbrains.kotlin:kotlin-bom:2.1.10'))

    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.lifecycle:lifecycle-livedata:2.10.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel:2.10.0'
    implementation 'androidx.navigation:navigation-fragment:2.9.6'
    implementation 'androidx.navigation:navigation-ui:2.9.6'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.2.0'
    implementation 'com.google.android.material:material:1.13.0'
}